/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AmbientEffects: typeof import('./src/components/AmbientEffects.vue')['default']
    Background: typeof import('./src/components/Background.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Live2DCompanion: typeof import('./src/components/Live2DCompanion.vue')['default']
    LoadChart: typeof import('./src/components/LoadChart.vue')['default']
    LoadingCover: typeof import('./src/components/LoadingCover.vue')['default']
    LoginDialog: typeof import('./src/components/LoginDialog.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    NodeCard: typeof import('./src/components/NodeCard.vue')['default']
    NodeGeneralCards: typeof import('./src/components/NodeGeneralCards.vue')['default']
    NodeList: typeof import('./src/components/NodeList.vue')['default']
    PingChart: typeof import('./src/components/PingChart.vue')['default']
    Provider: typeof import('./src/components/Provider.vue')['default']
    ResidualValueCalculator: typeof import('./src/components/ResidualValueCalculator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThreeNetworkTcpLatency: typeof import('./src/components/ThreeNetworkTcpLatency.vue')['default']
    TrafficProgress: typeof import('./src/components/TrafficProgress.vue')['default']
  }
}
